Added ability to specify a log group name
theonestack/hl-component-ecs-service pull request #62
Opened 2021-05-19 07:19 UTC by kyletbase2

2021-05-19 23:28 UTC, Guslington commented on ecs-service.cfndsl.rb
> +    LogGroupName "#{loggroup_name}"
Need to remove the string interpolation here as it turns the default Ref to 
```yaml
LogGroupName: "#<CfnDsl::RefDefinition:0x00007fca7d8bedc8>"
```

2021-05-19 23:29 UTC, Guslington requested changes
Need to remove the string interpolation

2021-05-21 02:40 UTC, kyletbase2 commented
Fixed @Guslington.

Without specifying a loggroup:
```
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Ref: AWS::StackName
      RetentionInDays: '7'
  TaskRole:
```

With one specified:
```
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: skynet-dmfx
      RetentionInDays: '7'
  TaskRole:
```

2021-05-31 00:08 UTC, Guslington approved these changes

2021-05-31 00:09 UTC, merged